default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: emma_development

test:
  <<: *default
  database: emma_test

production:
  <<: *default
  database: emma_production
  username: emma
  password:
