default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  host: postgres
  port: 5432

development:
  <<: *default
  database: emma_development

test:
  <<: *default
  database: emma_test

production:
  <<: *default
  database: emma_production
  username: emma
  password:
